name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    environment: main

    steps:
    - uses: actions/checkout@v4

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ~/cd-ci
          git pull origin main
          npm install
          npm run build
          pm2 restart cd-ci